# Generated by Django 4.1.7 on 2023-03-12 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='number_of_comments',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='item',
            name='number_of_votes',
            field=models.IntegerField(default=-1),
        ),
    ]
